import type { Metadata } from "next";
import { Playfair } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import About from "@/components/About";

const inter = Playfair({ 
  subsets: ['latin'],
  weight: '400'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        {children}
        <About />
        
      </body>
    </html>
  );
}
